#!/usr/bin/env node
/**
 * migrate-prod.mjs
 *
 * Production migration runner — reads DATABASE_URL directly from the
 * process environment (no --env-file=.env needed, because the container
 * doesn't have one and Coolify injects env vars at runtime).
 *
 * Runs in this order:
 *   1. create-db.ts       — idempotent CREATE DATABASE
 *   2. drizzle/0000_*.sql — base schema generated by drizzle-kit
 *   3. drizzle/0005_…_0010_*.sql — historical custom migrations
 *      (idempotent; safe to re-apply)
 *   4. apply-scraping-orchestration-migration.ts — bookkeeping
 *   5. seed-admin.ts      — default admin user
 *
 * Each step is logged. A failure aborts the whole run (no partial state
 * is committed) and exits non-zero so Coolify's post_deployment_command
 * surfaces the error.
 *
 * Usage:
 *   DATABASE_URL=postgres://... node scripts/db/migrate-prod.mjs
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import postgres from 'postgres'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..', '..')
const drizzleDir = join(repoRoot, 'drizzle')

const databaseUrl = process.env.DATABASE_URL
if (!databaseUrl) {
  console.error('❌  DATABASE_URL is not set.')
  process.exit(1)
}

function run(label, command, args, opts = {}) {
  console.log(`\n── ${label} ──`)
  execFileSync(command, args, {
    stdio: 'inherit',
    cwd: repoRoot,
    env: process.env,
    ...opts,
  })
}

async function applySqlInOrder() {
  const files = readdirSync(drizzleDir)
    .filter((f) => f.endsWith('.sql'))
    .sort()

  if (files.length === 0) {
    console.log('No .sql files in drizzle/ — skipping.')
    return
  }

  // Track applied migrations in `app_migrations` (created lazily).
  const sql = postgres(databaseUrl, { max: 1, prepare: false })
  try {
    await sql`
      CREATE TABLE IF NOT EXISTS app_migrations (
        name        text PRIMARY KEY,
        applied_at  timestamp NOT NULL DEFAULT now()
      )
    `

    for (const file of files) {
      const name = file.replace(/\.sql$/, '')
      const rows = await sql`
        SELECT EXISTS(SELECT 1 FROM app_migrations WHERE name = ${name}) AS exists
      `
      const existing = rows[0]
      if (existing?.exists) {
        console.log(`  · ${name} — already applied, skipping`)
        continue
      }

      console.log(`  · ${name} — applying…`)
      const sqlText = readFileSync(join(drizzleDir, file), 'utf8')

      // Try the whole file in one shot first — fastest path for fresh DBs
      // and the only safe way to apply PL/pgSQL `DO $$ ... $$;` blocks
      // (splitting on `;` corrupts them).
      try {
        await sql.unsafe(sqlText)
        await sql`INSERT INTO app_migrations (name) VALUES (${name})
                   ON CONFLICT (name) DO NOTHING`
        console.log(`  ✓ ${name} — applied (whole file)`)
        continue
      } catch (err) {
        const code = err && err.code
        const isAlreadyExists =
          code === '42P07' || // duplicate_table
          code === '42710' || // duplicate_object
          code === '42P06' || // duplicate schema
          code === '42P16'    // duplicate_index
        if (!isAlreadyExists) {
          // If the file is PL/pgSQL-heavy (DO blocks), we can't safely
          // split it. Re-throw.
          throw err
        }
        console.log(`  · ${name} — partial, falling back to per-statement`)
      }

      // Fallback: split on `--> statement-breakpoint` (Drizzle convention)
      // and execute each chunk in its own transaction. Chunks that contain
      // PL/pgSQL `DO $$ ... $$;` blocks are still atomic.
      const chunks = sqlText
        .split(/-->\s*statement-breakpoint/)
        .map((s) => s.trim())
        .filter((s) => s.length > 0)

      let applied = 0
      let skipped = 0
      for (const chunk of chunks) {
        try {
          await sql.unsafe(chunk)
          applied += 1
        } catch (err) {
          const code = err && err.code
          if (
            code === '42P07' ||
            code === '42710' ||
            code === '42P06' ||
            code === '42P16'
          ) {
            skipped += 1
            continue
          }
          throw err
        }
      }
      await sql`INSERT INTO app_migrations (name) VALUES (${name})
                 ON CONFLICT (name) DO NOTHING`
      console.log(`  ✓ ${name} — applied (${applied} new, ${skipped} skipped)`)
    }
  } finally {
    await sql.end({ timeout: 5 })
  }
}

async function main() {
  console.log('▸ migrate-prod — production migration runner')
  console.log(`  DATABASE_URL = ${maskUrl(databaseUrl)}`)
  console.log(`  drizzle/     = ${drizzleDir}`)

  // 1. Ensure target database exists
  run('1/5 create-db', 'pnpm', ['exec', 'tsx', 'scripts/db/create-db.ts'])

  // 2 + 3. Apply all SQL migrations in order
  console.log('\n── 2/3 apply SQL migrations ──')
  await applySqlInOrder()

  // 4. Bookkeeping for the orchestration migration
  run(
    '4/5 apply-scraping-orchestration-migration',
    'pnpm',
    ['exec', 'tsx', 'scripts/db/apply-scraping-orchestration-migration.ts'],
  )

  // 5. Default admin user
  run('5/5 seed-admin', 'pnpm', ['exec', 'tsx', 'scripts/db/seed-admin.ts'])

  console.log('\n✅  migrate-prod finished')
}

function maskUrl(url) {
  try {
    const u = new URL(url)
    if (u.password) u.password = '***'
    return u.toString()
  } catch {
    return '(unparseable)'
  }
}

main().catch((err) => {
  console.error('\n❌  migrate-prod failed:', err)
  process.exit(1)
})
