/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicPressRouteImport } from './routes/_public/press'
import { Route as PublicJournalRouteImport } from './routes/_public/journal'
import { Route as PublicFavoritesRouteImport } from './routes/_public/favorites'
import { Route as PublicExploreRouteImport } from './routes/_public/explore'
import { Route as PublicCookiesRouteImport } from './routes/_public/cookies'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as PublicListingSlugRouteImport } from './routes/_public/listing/$slug'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as AdminAdminScrapingIndexRouteImport } from './routes/_admin/admin/scraping/index'
import { Route as AdminAdminListingsIndexRouteImport } from './routes/_admin/admin/listings/index'
import { Route as AdminAdminScrapingSourcesRouteImport } from './routes/_admin/admin/scraping/sources'
import { Route as AdminAdminListingsNewRouteImport } from './routes/_admin/admin/listings/new'
import { Route as AdminAdminListingsIdRouteImport } from './routes/_admin/admin/listings/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPressRoute = PublicPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicJournalRoute = PublicJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFavoritesRoute = PublicFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicExploreRoute = PublicExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicListingSlugRoute = PublicListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminScrapingIndexRoute = AdminAdminScrapingIndexRouteImport.update({
  id: '/admin/scraping/',
  path: '/admin/scraping/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminListingsIndexRoute = AdminAdminListingsIndexRouteImport.update({
  id: '/admin/listings/',
  path: '/admin/listings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminScrapingSourcesRoute =
  AdminAdminScrapingSourcesRouteImport.update({
    id: '/admin/scraping/sources',
    path: '/admin/scraping/sources',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminListingsNewRoute = AdminAdminListingsNewRouteImport.update({
  id: '/admin/listings/new',
  path: '/admin/listings/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminListingsIdRoute = AdminAdminListingsIdRouteImport.update({
  id: '/admin/listings/$id',
  path: '/admin/listings/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof SignInRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/explore': typeof PublicExploreRoute
  '/favorites': typeof PublicFavoritesRoute
  '/journal': typeof PublicJournalRoute
  '/press': typeof PublicPressRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/listing/$slug': typeof PublicListingSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/listings/$id': typeof AdminAdminListingsIdRoute
  '/admin/listings/new': typeof AdminAdminListingsNewRoute
  '/admin/scraping/sources': typeof AdminAdminScrapingSourcesRoute
  '/admin/listings/': typeof AdminAdminListingsIndexRoute
  '/admin/scraping/': typeof AdminAdminScrapingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sign-in': typeof SignInRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/cookies': typeof PublicCookiesRoute
  '/explore': typeof PublicExploreRoute
  '/favorites': typeof PublicFavoritesRoute
  '/journal': typeof PublicJournalRoute
  '/press': typeof PublicPressRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/listing/$slug': typeof PublicListingSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/listings/$id': typeof AdminAdminListingsIdRoute
  '/admin/listings/new': typeof AdminAdminListingsNewRoute
  '/admin/scraping/sources': typeof AdminAdminScrapingSourcesRoute
  '/admin/listings': typeof AdminAdminListingsIndexRoute
  '/admin/scraping': typeof AdminAdminScrapingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/explore': typeof PublicExploreRoute
  '/_public/favorites': typeof PublicFavoritesRoute
  '/_public/journal': typeof PublicJournalRoute
  '/_public/press': typeof PublicPressRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_public/listing/$slug': typeof PublicListingSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/listings/$id': typeof AdminAdminListingsIdRoute
  '/_admin/admin/listings/new': typeof AdminAdminListingsNewRoute
  '/_admin/admin/scraping/sources': typeof AdminAdminScrapingSourcesRoute
  '/_admin/admin/listings/': typeof AdminAdminListingsIndexRoute
  '/_admin/admin/scraping/': typeof AdminAdminScrapingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/favorites'
    | '/journal'
    | '/press'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/listing/$slug'
    | '/admin/'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/scraping/sources'
    | '/admin/listings/'
    | '/admin/scraping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/favorites'
    | '/journal'
    | '/press'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/listing/$slug'
    | '/admin'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/scraping/sources'
    | '/admin/listings'
    | '/admin/scraping'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/sign-in'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/cookies'
    | '/_public/explore'
    | '/_public/favorites'
    | '/_public/journal'
    | '/_public/press'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/'
    | '/_admin/admin/login'
    | '/_public/listing/$slug'
    | '/_admin/admin/'
    | '/_admin/admin/listings/$id'
    | '/_admin/admin/listings/new'
    | '/_admin/admin/scraping/sources'
    | '/_admin/admin/listings/'
    | '/_admin/admin/scraping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/press': {
      id: '/_public/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PublicPressRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/journal': {
      id: '/_public/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof PublicJournalRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/favorites': {
      id: '/_public/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof PublicFavoritesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/explore': {
      id: '/_public/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof PublicExploreRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/listing/$slug': {
      id: '/_public/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof PublicListingSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/scraping/': {
      id: '/_admin/admin/scraping/'
      path: '/admin/scraping'
      fullPath: '/admin/scraping/'
      preLoaderRoute: typeof AdminAdminScrapingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/listings/': {
      id: '/_admin/admin/listings/'
      path: '/admin/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminAdminListingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/scraping/sources': {
      id: '/_admin/admin/scraping/sources'
      path: '/admin/scraping/sources'
      fullPath: '/admin/scraping/sources'
      preLoaderRoute: typeof AdminAdminScrapingSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/listings/new': {
      id: '/_admin/admin/listings/new'
      path: '/admin/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminAdminListingsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/listings/$id': {
      id: '/_admin/admin/listings/$id'
      path: '/admin/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminAdminListingsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminListingsIdRoute: typeof AdminAdminListingsIdRoute
  AdminAdminListingsNewRoute: typeof AdminAdminListingsNewRoute
  AdminAdminScrapingSourcesRoute: typeof AdminAdminScrapingSourcesRoute
  AdminAdminListingsIndexRoute: typeof AdminAdminListingsIndexRoute
  AdminAdminScrapingIndexRoute: typeof AdminAdminScrapingIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminListingsIdRoute: AdminAdminListingsIdRoute,
  AdminAdminListingsNewRoute: AdminAdminListingsNewRoute,
  AdminAdminScrapingSourcesRoute: AdminAdminScrapingSourcesRoute,
  AdminAdminListingsIndexRoute: AdminAdminListingsIndexRoute,
  AdminAdminScrapingIndexRoute: AdminAdminScrapingIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicExploreRoute: typeof PublicExploreRoute
  PublicFavoritesRoute: typeof PublicFavoritesRoute
  PublicJournalRoute: typeof PublicJournalRoute
  PublicPressRoute: typeof PublicPressRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicListingSlugRoute: typeof PublicListingSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCookiesRoute: PublicCookiesRoute,
  PublicExploreRoute: PublicExploreRoute,
  PublicFavoritesRoute: PublicFavoritesRoute,
  PublicJournalRoute: PublicJournalRoute,
  PublicPressRoute: PublicPressRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicListingSlugRoute: PublicListingSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
